let topicDATA = {}

if(localStorage.getItem('language') === 'zh'){

topicDATA['10'] = {"code":1,"msg":"请求成功","time":"1588044262","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/3e413c6b8aba600bb828d145f32fc64f.png","total":5,"rows":[{"id":50,"provice_id":10,"answer":"A","question":"数据显示，北京市集聚了3.5万家外国常驻机构、4000多家地区总部和研发中心，53家世界500强企业总部，居世界 （ ） ？","option":[{"num":"A","value":"A 第一 "},{"num":"B","value":"B 第十 "},{"num":"C","value":"C 第二十"}]},{"id":49,"provice_id":10,"answer":"C","question":"2019年10月,世界银行发布《全球营商环境报告2020》中，北京作为样本城市，营商环境在全球排名（  ） ？","option":[{"num":"A","value":"A 前10  "},{"num":"B","value":"B 前20 "},{"num":"C","value":" C 前30"}]},{"id":48,"provice_id":10,"answer":"A","question":"2018年，北京人均GDP位于全国 （  ） ？","option":[{"num":"A","value":"A 第一 "},{"num":"B","value":"B 第二 "},{"num":"C","value":"C 第三"}]},{"id":47,"provice_id":10,"answer":"B","question":"北京是中国的政治中心、文化中心、国际交往中心和 （   ） ？","option":[{"num":"A","value":"A 经济中心 "},{"num":"B","value":"B 科技创新中心 "},{"num":"C","value":"C 金融中心"}]},{"id":46,"provice_id":10,"answer":"A","question":"北京的地理位置位于华北平原?","option":[{"num":"A","value":"A北部 "},{"num":"B","value":"B南部 "},{"num":"C","value":"C东部"}]}]}}

topicDATA['9'] = {"code":1,"msg":"请求成功","time":"1588044529","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/8d0c85d6b28e1ed833c523f29c30ae81.png","total":5,"rows":[{"id":20,"provice_id":9,"answer":"B","question":"中国大陆首个自贸区设立在哪个城市？","option":[{"num":"A","value":"A. 北京"},{"num":"B","value":"B.上海"},{"num":"C","value":"C.深圳"}]},{"id":19,"provice_id":9,"answer":"C","question":"上海位列全球金融中心指数（GFCI）第几名？","option":[{"num":"A","value":"A. 10"},{"num":"B","value":"B. 15"},{"num":"C","value":"C.5"}]},{"id":18,"provice_id":9,"answer":"A","question":"为提升上海参与国际合作的竞争力，2019年8月上海出台了哪项新措施？","option":[{"num":"A","value":"A. 上海市新一轮服务业扩大开放若干措施"},{"num":"B","value":"B. 扩大开放100条"},{"num":"C","value":"C. 外资33条"}]},{"id":17,"provice_id":9,"answer":"C","question":"上海港集装箱吞吐量连续几年世界第一？","option":[{"num":"A","value":"A. 5"},{"num":"B","value":"B. 7"},{"num":"C","value":"C. 9"}]},{"id":16,"provice_id":9,"answer":"A","question":"上海财政收入占全国财政收入的比例是多少？","option":[{"num":"A","value":"A. 十分之一"},{"num":"B","value":"B. 十五分之一"},{"num":"C","value":"C.二十分之一"}]}]}}


topicDATA['8'] = {"code":1,"msg":"请求成功","time":"1588044567","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/b160e3fc19abf1ae1b280f64aff3b017.png","total":5,"rows":[{"id":45,"provice_id":8,"answer":"C","question":" 重庆最出名的美食是？","option":[{"num":"A","value":"A. 烤鸭 "},{"num":"B","value":"B. 白切鸡 "},{"num":"C","value":"C. 火锅"}]},{"id":44,"provice_id":8,"answer":"A","question":"  重庆的优势产业是？","option":[{"num":"A","value":"A. 汽车、电子信息 "},{"num":"B","value":"B. 装备、材料 "},{"num":"C","value":"C. 生物医药"}]},{"id":43,"provice_id":8,"answer":"A","question":"陆海新通道的运营中心是？","option":[{"num":"A","value":"A. 重庆 "},{"num":"B","value":"B. 贵州 "},{"num":"C","value":"C. 广西"}]},{"id":42,"provice_id":8,"answer":"B","question":"重庆与多少个国家和地区开展了经贸往来？","option":[{"num":"A","value":"A. 190 "},{"num":"B","value":"B. 224 "},{"num":"C","value":"C. 993"}]},{"id":41,"provice_id":8,"answer":"C","question":"重庆的国际物流体系涵盖哪些运输网络？","option":[{"num":"A","value":"A. 铁、公、水联运"},{"num":"B","value":"B. 公、水、空联运"},{"num":"C","value":"C.铁、公、水、空联运"}]}]}}

topicDATA['7'] = {"code":1,"msg":"请求成功","time":"1588044779","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/9fd2bd8baf90b1e8f24ccee2dcd45913.png","total":5,"rows":[{"id":35,"provice_id":7,"answer":"B","question":"下列哪些矿产资源为新疆维吾尔自治区最具优势的资源？","option":[{"num":"A","value":"A.铁矿"},{"num":"B","value":"B.石油天然气"},{"num":"C","value":"C.煤矿"}]},{"id":34,"provice_id":7,"answer":"C","question":"下列哪些国家及地区是新疆维吾尔自治区的主要对外合作伙伴？","option":[{"num":"A","value":"A.韩国"},{"num":"B","value":"B.日本"},{"num":"C","value":"C.哈萨克斯坦"}]},{"id":33,"provice_id":7,"answer":"B","question":"新疆维吾尔自治区目前共与多少个“一带一路”国家发展合作？","option":[{"num":"A","value":"A.20个"},{"num":"B","value":"B.36个"},{"num":"C","value":"C.30个"}]},{"id":32,"provice_id":7,"answer":"C","question":"在新疆维吾尔自治区2018年GDP 中占比最高的产业是？","option":[{"num":"A","value":"A.第一产业"},{"num":"B","value":"B.第二产业"},{"num":"C","value":"C.第三产业"}]},{"id":31,"provice_id":7,"answer":"C","question":"下列著名景区哪个属于新疆地区的？","option":[{"num":"A","value":"A.锡林郭勒草原"},{"num":"B","value":"B.贺兰山"},{"num":"C","value":"C.天山天池"}]}]}}

topicDATA['6'] = {"code":1,"msg":"请求成功","time":"1588044807","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/bcb8abe1527df37571b223ea25fbfb0f.png","total":5,"rows":[{"id":10,"provice_id":6,"answer":"B","question":"2018年四川省GDP总值在全国排名第几？","option":[{"num":"A","value":"A.第二"},{"num":"B","value":"B.第六"},{"num":"C","value":"C.第八"}]},{"id":9,"provice_id":6,"answer":"C","question":"四川省有多少个少数民族？","option":[{"num":"A","value":"A.24个"},{"num":"B","value":"B.48个"},{"num":"C","value":"C.55个"}]},{"id":8,"provice_id":6,"answer":"C","question":" 四川省拥有多少种金属、非金属矿产？","option":[{"num":"A","value":"A.50"},{"num":"B","value":"B.82"},{"num":"C","value":"C.132"}]},{"id":7,"provice_id":6,"answer":"C","question":"全球 500 强企业中，有多少家已在四川省落户？","option":[{"num":"A","value":"A.156"},{"num":"B","value":"B.189"},{"num":"C","value":"C.285"}]},{"id":6,"provice_id":6,"answer":"B","question":"四川省的省会是下列哪个城市？","option":[{"num":"A","value":"A.宜宾"},{"num":"B","value":"B.成都"},{"num":"C","value":"C.自贡"}]}]}}

topicDATA['5'] = {"code":1,"msg":"请求成功","time":"1588044810","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/a6d651867bd159ec9be7f21555957352.png","total":5,"rows":[{"id":40,"provice_id":5,"answer":"C","question":"以下哪个不是安徽的企业？","option":[{"num":"A","value":"A.  海螺水泥"},{"num":"B","value":"B. 丰原集团"},{"num":"C","value":"C. 宇通集团"}]},{"id":39,"provice_id":5,"answer":"C","question":"2018年，哪家安徽企业与德国大众合资生产的新能源汽车顺利下线？","option":[{"num":"A","value":"A. 奇瑞汽车"},{"num":"B","value":"B.华菱汽车"},{"num":"C","value":"C. 江淮汽车"}]},{"id":38,"provice_id":5,"answer":"B","question":"安徽省与下列哪个经济区域紧密相连？","option":[{"num":"A","value":"A. 京津冀经济区"},{"num":"B","value":"B. 长江三角洲经济区"},{"num":"C","value":"C. 珠江三角洲经济区"}]},{"id":37,"provice_id":5,"answer":"A","question":"40年前，哪个村的“大包干”拉开了中国农村改革的大幕？","option":[{"num":"A","value":"A. 小岗村"},{"num":"B","value":"B. 华西村"},{"num":"C","value":"C. 大寨村"}]},{"id":36,"provice_id":5,"answer":"C","question":"下列哪个选项是安徽的世界与文化双重遗产？","option":[{"num":"A","value":"A.九华山"},{"num":"B","value":"B.琅琊山"},{"num":"C","value":"C.黄山"}]}]}}

topicDATA['4'] = {"code":1,"msg":"请求成功","time":"1588044815","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/caa8b5f50a7893068f1c6d38d84b1b70.png","total":5,"rows":[{"id":15,"provice_id":4,"answer":"A","question":"以下哪个是宁夏鼓励外商投资重点行业？","option":[{"num":"A","value":"A.枸杞、葡萄、马铃薯的种植和深加工"},{"num":"B","value":"B.奶制品生产"},{"num":"C","value":"C.多晶硅加工"}]},{"id":14,"provice_id":4,"answer":"A","question":"宁夏在哪一年被明确为“一带一路”重要节点？","option":[{"num":"A","value":"A. 2015 "},{"num":"B","value":"B. 2016"},{"num":"C","value":"C. 2017"}]},{"id":13,"provice_id":4,"answer":"B","question":"以下关于宁夏五宝的描述正确的是？","option":[{"num":"A","value":"A. 枸杞、甘草、贺兰石、滩羊肉、黄花菜"},{"num":"B","value":"B. 枸杞、甘草、贺兰石、滩羊皮、发菜"},{"num":"C","value":"C. 枸杞、黄芪、贺兰石、滩羊皮、发菜"}]},{"id":12,"provice_id":4,"answer":"B","question":"以下哪个国家是宁夏的主要投资目的地？","option":[{"num":"A","value":"A. 印尼"},{"num":"B","value":"B. 澳大利亚"},{"num":"C","value":"C. 文莱"}]},{"id":11,"provice_id":4,"answer":"C","question":"宁夏回族自治区成立于哪一年？","option":[{"num":"A","value":"A. 1949"},{"num":"B","value":"B.1954"},{"num":"C","value":"C.1958"}]}]}}

topicDATA['3'] = {"code":1,"msg":"请求成功","time":"1588044859","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/187659b8e18b413fc30ab95f70c2f62b.png","total":5,"rows":[{"id":25,"provice_id":3,"answer":"B","question":"广西正积极构建构建“南向、北联、东融、西合”新格局，对其理解不正确的是？","option":[{"num":"A","value":"A.向南畅通国际陆海贸易新通道"},{"num":"B","value":"B.向北深化参与京津冀一体化战略布局"},{"num":"C","value":"C.向东对接融入粤港澳大湾区建设"}]},{"id":24,"provice_id":3,"answer":"C","question":"广西北部湾港是一些省市最便捷的出海口，以下哪个不对？","option":[{"num":"A","value":"A.四川"},{"num":"B","value":"B.重庆"},{"num":"C","value":"C.海南"}]},{"id":23,"provice_id":3,"answer":"B","question":"大力发展现代特色农业的广西，生产了全国__以上的甘蔗、约50%的蚕茧、45%以上的木材。","option":[{"num":"A","value":"A.90%"},{"num":"B","value":"B.60%"},{"num":"C","value":"C. 50%"}]},{"id":22,"provice_id":3,"answer":"C","question":"以下哪个不是广西的企业？","option":[{"num":"A","value":"A.北部湾投资"},{"num":"B","value":"B.玉柴机器"},{"num":"C","value":"C.哇哈哈"}]},{"id":21,"provice_id":3,"answer":"A","question":"广西是矿产资源富集区，素有\"有色金属之乡\"的称号，其中哪种储量居世界之冠？","option":[{"num":"A","value":"A.铟"},{"num":"B","value":"B.锰"},{"num":"C","value":"C.锡"}]}]}}

topicDATA['1'] = {"code":1,"msg":"请求成功","time":"1588044899","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/a7f3f3d8895525f2cd6e78b57a23b760.png","total":5,"rows":[{"id":5,"provice_id":1,"answer":"C","question":" 以下哪个不是贵州省的title？","option":[{"num":"A","value":"A. 首批内陆开放型经济试验区 "},{"num":"B","value":"B.首个大数据试验区 "},{"num":"C","value":"C.首批国家级金融改革试验区"}]},{"id":4,"provice_id":1,"answer":"C","question":"贵州有多少个少数民族？","option":[{"num":"A","value":"A. 34个 "},{"num":"B","value":"B. 48个 "},{"num":"C","value":"C.55个"}]},{"id":3,"provice_id":1,"answer":"B","question":" 以下哪个不属于2017年后贵州省制定的三大战略行动？","option":[{"num":"A","value":"A. 大生态"},{"num":"B","value":" B. 大旅游 "},{"num":"C","value":"C. 大数据"}]},{"id":2,"provice_id":1,"answer":"A","question":"贵州的GDP增速在全国属于哪一梯队？","option":[{"num":"A","value":"A. Top 5"},{"num":"B","value":"B. Top 10"},{"num":"C","value":"C. Top 20"}]},{"id":1,"provice_id":1,"answer":"A","question":"以下哪个不是贵州省的世界自然遗产？","option":[{"num":"A","value":"A.西递 "},{"num":"B","value":"B.赤水 "},{"num":"C","value":"C.梵净山"}]}]}}
}else{
	
topicDATA['10'] = {"code":1,"msg":"请求成功","time":"1588132435","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/3e413c6b8aba600bb828d145f32fc64f.png","total":5,"rows":[{"id":50,"provice_id":10,"answer":"A","question":"Beijing is home to 35,000 foreign resident institutions, over 4,000 regional headquarters and R&D centers and 53 headquarters of Fortune Global 500 companies, ranking   （    ）  in the world?","option":[{"num":"A","value":"A the first  "},{"num":"B","value":"B the tenth  "},{"num":"C","value":"C the twentieth "}]},{"id":49,"provice_id":10,"answer":"C","question":"According to the Doing Business 2020 issued by the World Bank in October of 2019, as a sample city, Beijing ranked among  （  ）  in the world?","option":[{"num":"A","value":"A the Top 10 "},{"num":"B","value":"B the Top 20  "},{"num":"C","value":"C the Top 30"}]},{"id":48,"provice_id":10,"answer":"A","question":"In 2018, Beijing's per capita GDP reached 21,300 U.S. dollars, ranking （  ）in China?","option":[{"num":"A","value":"A the first "},{"num":"B","value":"B the second  "},{"num":"C","value":"C the third"}]},{"id":47,"provice_id":10,"answer":"B","question":"Beijing is not only China's political and cultural center, but also the center of global exchange and  （  ）  ","option":[{"num":"A","value":"A economy  "},{"num":"B","value":"B technological innovation  "},{"num":"C","value":"C finance"}]},{"id":46,"provice_id":10,"answer":"A","question":"Beijing is located in the （    ）part of the North China Plain?","option":[{"num":"A","value":"A northern  "},{"num":"B","value":"B southern  "},{"num":"C","value":"C eastern"}]}]}}

topicDATA['9'] = {"code":1,"msg":"请求成功","time":"1588132496","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/8d0c85d6b28e1ed833c523f29c30ae81.png","total":5,"rows":[{"id":20,"provice_id":9,"answer":"B","question":"In which city has China established the first pilot free trade zone? ","option":[{"num":"A","value":"A. Beijing"},{"num":"B","value":"B. Shanghai"},{"num":"C","value":"C. Shenzhen"}]},{"id":19,"provice_id":9,"answer":"C","question":"What’s the rank of Shanghai in the Global Financial Centers Index (GFCI)?","option":[{"num":"A","value":"A. No. 10"},{"num":"B","value":"B. No. 15"},{"num":"C","value":"C.No.5"}]},{"id":18,"provice_id":9,"answer":"A","question":"Which of the following policy is newly introduced by the Shanghai municipal government in August 2019 to enhance the competitiveness of Shanghai's participation in international cooperation?","option":[{"num":"A","value":"A. The policy for expanding the opening-up of the service sector"},{"num":"B","value":"B. The 100 new measures for a more open shanghai"},{"num":"C","value":"C. The 33 measures to attract more foreign capital"}]},{"id":17,"provice_id":9,"answer":"C","question":"How many years in a row has Shanghai Port been number one in the world by container throughput?","option":[{"num":"A","value":"A. 5 years"},{"num":"B","value":"B. 7 years"},{"num":"C","value":"C. 9 years"}]},{"id":16,"provice_id":9,"answer":"A","question":"What is the ratio of Shanghai's fiscal revenue to the national fiscal revenue?","option":[{"num":"A","value":"A. One in ten"},{"num":"B","value":"B. One in fifteen"},{"num":"C","value":"C. One in twenty"}]}]}}


topicDATA['8'] = {"code":1,"msg":"请求成功","time":"1588132501","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/b160e3fc19abf1ae1b280f64aff3b017.png","total":5,"rows":[{"id":45,"provice_id":8,"answer":"C","question":" What is the most famous food of Chongqing？","option":[{"num":"A","value":"A. roast duck  "},{"num":"B","value":"B. Sliced boiled chicken  "},{"num":"C","value":"C. hot pot"}]},{"id":44,"provice_id":8,"answer":"A","question":"   What is\/are Chongqing’s advantageous industries? ","option":[{"num":"A","value":"A. automobile, electronic information "},{"num":"B","value":"B. equipment, materials "},{"num":"C","value":"C. biomedical sectors"}]},{"id":43,"provice_id":8,"answer":"A","question":"  Which is the operation of the New International Land-Sea Trade Corridor?","option":[{"num":"A","value":"A. Chongqing "},{"num":"B","value":"B. Guizhou "},{"num":"C","value":"C. Guangxi"}]},{"id":42,"provice_id":8,"answer":"B","question":"  How many countries and regions has Chongqing carried out economic and trade exchanges with？","option":[{"num":"A","value":"A. 190 "},{"num":"B","value":"B. 224 "},{"num":"C","value":"C. 993"}]},{"id":41,"provice_id":8,"answer":"C","question":"  What transport network does Chongqing’s international logistics system include?","option":[{"num":"A","value":"A. rail, road, water transport"},{"num":"B","value":"B.road, water, air transport"},{"num":"C","value":"C.rail, road, water, air transport "}]}]}}


topicDATA['7'] = {"code":1,"msg":"请求成功","time":"1588132593","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/9fd2bd8baf90b1e8f24ccee2dcd45913.png","total":5,"rows":[{"id":35,"provice_id":7,"answer":"B","question":"Which of the following mineral resources is the most advantageous resource in Xinjiang Uygur Autonomous Region?","option":[{"num":"A","value":"A. iron ore"},{"num":"B","value":"B. oil and gas"},{"num":"C","value":"C. coal mine"}]},{"id":34,"provice_id":7,"answer":"C","question":"Which of the following countries and regions are the major foreign trading partners of Xinjiang Uygur Autonomous Region?","option":[{"num":"A","value":"A. Republic of Korea"},{"num":"B","value":"B. Japan"},{"num":"C","value":"C.Kazakhstan"}]},{"id":33,"provice_id":7,"answer":"B","question":"By far, how many of the Belt and Road (B&R) countries have developed cooperation with Xinjiang Uygur Autonomous Region?","option":[{"num":"A","value":"A. 20"},{"num":"B","value":"B.36"},{"num":"C","value":"C30"}]},{"id":32,"provice_id":7,"answer":"C","question":"What is the industry with the highest proportion of GDP in Xinjiang Uygur Autonomous Region in 2018?","option":[{"num":"A","value":"A. Primary Industry"},{"num":"B","value":"B. Secondary Industry"},{"num":"C","value":"C. Tertiary Industry"}]},{"id":31,"provice_id":7,"answer":"C","question":"Which of the following famous scenic spots is located in Xinjiang?","option":[{"num":"A","value":"A. XiIin GoI Prairie"},{"num":"B","value":"B. Helan Mountain"},{"num":"C","value":"C. Tianchi (Heavenly Lake) on Tianshan (Heavenly Mountain)"}]}]}}

topicDATA['6'] = {"code":1,"msg":"请求成功","time":"1588132596","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/bcb8abe1527df37571b223ea25fbfb0f.png","total":5,"rows":[{"id":10,"provice_id":6,"answer":"B","question":"What’s the rank of the GDP of Sichuan province in China in the year 2018?","option":[{"num":"A","value":"A. Second"},{"num":"B","value":"B. Sixth"},{"num":"C","value":"C. Eighth"}]},{"id":9,"provice_id":6,"answer":"C","question":"How many ethnic minorities are there in Sichuan?","option":[{"num":"A","value":"A.24"},{"num":"B","value":"B.48"},{"num":"C","value":"C.55"}]},{"id":8,"provice_id":6,"answer":"C","question":" How many kinds of metal and non-metallic minerals are there in Sichuan?","option":[{"num":"A","value":"A.50"},{"num":"B","value":"B.82"},{"num":"C","value":"C.132"}]},{"id":7,"provice_id":6,"answer":"C","question":"How many Fortune 500 companies have settled in Sichuan?","option":[{"num":"A","value":"A.156"},{"num":"B","value":"B.189"},{"num":"C","value":"C.285"}]},{"id":6,"provice_id":6,"answer":"B","question":"Which of the following is the capital of Sichuan province?","option":[{"num":"A","value":"A. Yibin"},{"num":"B","value":"B. Chengdu"},{"num":"C","value":"C. Zigong"}]}]}}

topicDATA['5'] = {"code":1,"msg":"请求成功","time":"1588132598","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/a6d651867bd159ec9be7f21555957352.png","total":5,"rows":[{"id":40,"provice_id":5,"answer":"C","question":"Which of the following companies is not in Anhui?","option":[{"num":"A","value":"A.Conch Cement"},{"num":"B","value":"B. BBCA Group"},{"num":"C","value":"C. Yutong Bus"}]},{"id":39,"provice_id":5,"answer":"C","question":"Which automobile company of Anhui established a new energy vehicle (NEV) joint venture with Volkswagen of Germany and the plant commenced operation in 2018?","option":[{"num":"A","value":"A. Chery"},{"num":"B","value":"B. Hualing Xingma"},{"num":"C","value":"C. JAC Motors"}]},{"id":38,"provice_id":5,"answer":"B","question":"Which of the following economic regions neighbour with Anhui?","option":[{"num":"A","value":"A. Beijing-Tianjin-Hebei "},{"num":"B","value":"B. Yangtze River Delta"},{"num":"C","value":"C. Pearl River Delta"}]},{"id":37,"provice_id":5,"answer":"A","question":"Forty years ago, which village unveiled the curtain for China’s rural reform? ","option":[{"num":"A","value":"A. Xiaogang Village"},{"num":"B","value":"B. Huaxi Village"},{"num":"C","value":"C. Dazhai Village"}]},{"id":36,"provice_id":5,"answer":"C","question":"Which of the following mountains is a World Cultural and Natural Heritage in Anhui?","option":[{"num":"A","value":"A. Jiuhua Mountain"},{"num":"B","value":"B. Langya Mountain"},{"num":"C","value":"C. Mount Huangshan"}]}]}}

topicDATA['4'] = {"code":1,"msg":"请求成功","time":"1588132638","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/caa8b5f50a7893068f1c6d38d84b1b70.png","total":5,"rows":[{"id":15,"provice_id":4,"answer":"A","question":"Which of the following is Ningxia's key industry where foreign investment is encouraged?","option":[{"num":"A","value":"A. Planting and deep processing of Chinese wolfberry, grape and potatoes"},{"num":"B","value":"B. Production of dairy products"},{"num":"C","value":"C. Processing of polycrystalline silicon"}]},{"id":14,"provice_id":4,"answer":"A","question":"In which year was Ningxia designated as an important Belt and Road node?","option":[{"num":"A","value":"A. 2015 "},{"num":"B","value":"B. 2016"},{"num":"C","value":"C. 2017"}]},{"id":13,"provice_id":4,"answer":"B","question":"Which of the following are the \"five treasures of Ningxia\"?","option":[{"num":"A","value":"A. Licorice, Helan stone, Tan sheepskin, Chinese wolfberry and Daylily"},{"num":"B","value":"B. Licorice, Helan stone, Tan sheepskin, Chinese wolfberry and Long-thread moss"},{"num":"C","value":"C. Licorice, Astragalus membranaceus, Helan stone, Tan sheepskin and Long-thread moss"}]},{"id":12,"provice_id":4,"answer":"B","question":"Which of the following is the main investment destination of Ningxia?","option":[{"num":"A","value":"A. Indonesia "},{"num":"B","value":"B. Australia"},{"num":"C","value":"C. Brunei"}]},{"id":11,"provice_id":4,"answer":"C","question":"When was the Ningxia Hui Autonomous Region founded?","option":[{"num":"A","value":"A. 1949"},{"num":"B","value":"B.1954"},{"num":"C","value":"C.1958"}]}]}}

topicDATA['3'] = {"code":1,"msg":"请求成功","time":"1588132643","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/187659b8e18b413fc30ab95f70c2f62b.png","total":5,"rows":[{"id":25,"provice_id":3,"answer":"B","question":"Guangxi is now accelerating opening-up on all fronts, which of the following is not correct?","option":[{"num":"A","value":"A. To the south: Dredge the New International Land-Sea Trade Corridor"},{"num":"B","value":"B. To the north: Deepen cooperation with the Yangtze River Economic Zone"},{"num":"C","value":"C. To the east: Dock with the construction of Guangdong-Hong Kong-Macao Greater Bay Area"}]},{"id":24,"provice_id":3,"answer":"C","question":"Guangxi Beibu Gulf port is the most convenient sea portal for some inland provinces and cities, which one of the following is NOT one of them?","option":[{"num":"A","value":"A.Sichuan"},{"num":"B","value":"B.Chongqing"},{"num":"C","value":"C.Hainan"}]},{"id":23,"provice_id":3,"answer":"B","question":"China Guangxi is known for its agricultural development, it produces more than__of the country’s sugar cane output, and more than 50 percent silkworm cocoon, more than 45 percent wood.","option":[{"num":"A","value":"A.90 percent"},{"num":"B","value":"B.60 percent"},{"num":"C","value":"C.50 percent"}]},{"id":22,"provice_id":3,"answer":"C","question":"Which one of the following companies is NOT from Guangxi?","option":[{"num":"A","value":"A.Beibu Gulf Investment Group"},{"num":"B","value":"B.Yuchai Machinery Group"},{"num":"C","value":"C.Wahaha"}]},{"id":21,"provice_id":3,"answer":"A","question":"Guangxi Zhuang Autonomous Region boasts abundant mineral resources especially non-ferrous metals. Do you know which of the following that Guangxi has reserves that top the world?","option":[{"num":"A","value":"A.Indium"},{"num":"B","value":"B.Manganese"},{"num":"C","value":"C.Tin"}]}]}}

topicDATA['1'] = {"code":1,"msg":"请求成功","time":"1588132647","data":{"cover":"http:\/\/xhsilkroad.5xing.com.cn\/uploads\/20200220\/a7f3f3d8895525f2cd6e78b57a23b760.png","total":5,"rows":[{"id":5,"provice_id":1,"answer":"C","question":"Which of the following is not the \"title\" of Guizhou?","option":[{"num":"A","value":"A. the first batch of inland open economic pilot zones"},{"num":"B","value":" B. the first big data pilot zone"},{"num":"C","value":" C. the first batch of national financial reform pilot zones"}]},{"id":4,"provice_id":1,"answer":"C","question":"How many ethnic minorities are there in Guizhou?","option":[{"num":"A","value":"A. 34"},{"num":"B","value":" B. 48 "},{"num":"C","value":"C. 55"}]},{"id":3,"provice_id":1,"answer":"B","question":" Which of the following does not belong to the Three Strategic Actions formulated by Guizhou province in 2017?","option":[{"num":"A","value":"A. Big ecology "},{"num":"B","value":"B. Big tourism "},{"num":"C","value":"C. Big data"}]},{"id":2,"provice_id":1,"answer":"A","question":"What’s the rank of Guizhou's GDP growth rate in China?","option":[{"num":"A","value":"A. Top 5"},{"num":"B","value":"B. Top 10"},{"num":"C","value":"C. Top 20"}]},{"id":1,"provice_id":1,"answer":"A","question":" Which of the following is not a World Natural Heritage Site in Guizhou?","option":[{"num":"A","value":"A.Xidi "},{"num":"B","value":"B.Chishui "},{"num":"C","value":"C.Mount Fanjingshan"}]}]}}

}
function getTopic(id){
	return topicDATA[id];
}